# Create a diagram for node deployment and service
# Use example of nginx deployment and service
# Nodeapp deployment to have 3 pods min -
# service within the same cluster and namespace to connect to node deploy
# type LoadBalancer
# End goal is to see our nodeapp running on localhost:3000
# The working image of our node-app
# allow port 3000 and 80

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  selector:
    matchLabels:
      app: node
  replicas: 3
  template:
    metadata:
      labels:
        app: node
    spec:
      containers: 
        - name: node
          image: zeeshanj/sre_node_app:latest

          ports:
            - containerPort: 3000
          
          env:
          - name: DB_HOST
            value: mongodb://mongo:27017/posts
