# Create a file called node_hpa.yml
# Create an Autoscaling group for our node app

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler #(hpa)

metadata:
  name: sparta-node-app-deploy
  namespace: default

spec:
  maxReplicas: 9 #(max number of instances/pods)
  minReplicas: 1 #(min number of instances/pods)
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node
  targetCPUUtilizationPercentage: 50 # 50% of CPU use
  
